### ISSUE TITLE
ENOENT: no such file or directory, open './package.json'.

### ISSUE THREAD

**Issue by itSubeDibesh** [Sniper-Code/SniperCode.FileSystem.Cli#1]
### **ENOENT: no such file or directory, open './package.json'.**

```error
$ sfs
node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open './package.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Function.read_file (/home/user/.nvm/versions/node/v16.13.2/lib/node_modules/snipercode.filesystem.cli/node_modules/snipercode.filesystem/src/fs.js:99:46)
    at Details.#GetPackageJson (file:///home/user/.nvm/versions/node/v16.13.2/lib/node_modules/snipercode.filesystem.cli/config/details.js:19:51)
    at Details.getDetails (file:///home/user/.nvm/versions/node/v16.13.2/lib/node_modules/snipercode.filesystem.cli/config/details.js:29:45)
    at file:///home/user/.nvm/versions/node/v16.13.2/lib/node_modules/snipercode.filesystem.cli/index.js:10:29
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './package.json'
}

```
The issue ([SniperCode.FileSystem.Cli v1.0.0](https://github.com/Sniper-Code/SniperCode.FileSystem.Cli/releases/tag/v1.0.0)) was detected on Linux system ([Ubuntu 2021.4](https://ubuntu.com/download/desktop))

**Comment by itSubeDibesh** [comment]
A bug fix has been made in [**v1.0.1**](https://github.com/Sniper-Code/SniperCode.FileSystem.Cli/releases/tag/v1.0.1). Checkout the [release section](https://github.com/Sniper-Code/SniperCode.FileSystem.Cli/releases).
